package com.vectorx.spring5.s13_aspectj_annatation;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class TestAspectJ {
    public static void main(String[] args) {
        ApplicationContext context = new ClassPathXmlApplicationContext("bean11.xml");
        User user = context.getBean("user", User.class);
        user.add();
        //around before...
        //before...
        //add...
        //afterReturning...
        //after...
        //around after...
    }
}
