package com.vectorx.spring5.s14_aspectj_xml;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class TestAspectJ {
    public static void main(String[] args) {
        ApplicationContext context = new ClassPathXmlApplicationContext("bean12.xml");
        Book book = context.getBean("book", Book.class);
        book.buy();
        //before...
        //around before...
        //buy...
        //around after...
        //after...
        //afterReturning...
    }
}
